# -*- coding: utf-8 -*-
"""Student_Attendance_Performance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aP_cOpPuTlTbaXmsafb4QXKrmxu26M1w

# Project Title

# Student Performance and Attendance Analyser

# Problem Statement
Educational institutions need to analyze student performance and attendance to identify patterns, weak
areas, and overall outcomes.
This project analyzes academic records to support data-driven decisions.

#Pandas
"""

import pandas as pd

df = pd.read_excel("Student Academic Performance.xlsx")

# unerstand data
df.head()

df.info()

df.describe()

print(df.shape)

print(df.columns)

print(df.dtypes)

# data cleaning

df.isnull().sum()

df.fillna(0, inplace=True)

# data analysis
print("Average GPA:",df["GPA"].mean())

print(df["Absence Days Under-7"].value_counts())

# group based analysis
print(df.groupby("Course")["GPA"].mean())

print(df.groupby("Absence Days Under-7")["GPA"].mean())

"""#EDA process and data visualization"""

#Histograms for GPA distribution
import pandas as pd
import matplotlib.pyplot as plt
plt.hist(df['GPA'],bins=10)
plt.title("GPA Distribution")
plt.xlabel("GPA")
plt.ylabel("Number of students")
plt.show()

#Bar plots for attendance categories
import seaborn as sns
sns.barplot(x=df['Absence Days Under-7'],y='GPA',data=df)
plt.title("Absence vs performance")
plt.xlabel("Absence Days")
plt.ylabel("GPA")
plt.show()

#Box plot for subject-wise performance
import seaborn as sns
sns.boxplot(x='Course',y='GPA',data=df)
plt.title("SUbject-wise Performance")
plt.xlabel("Subject")
plt.ylabel("GPA")
plt.show()

"""# conclusion:
* The analysis shows that student performance infulenced by attendance and Course
* Students with regular attendance have achive higher GPA
* Most students score least GPA in science couse
* Students with less than 7 absence days peform better than other
* Attendance plays a significant role in academic performance
* Enhancing attendance and focusing on weaker Course can improve academic performance
"""