# -*- coding: utf-8 -*-
"""week_2_Da_Assignment_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SE22Jlv2n3m6Qqq1PqIEx9Mh0pOe7T1J

#Assignment 1

#Sales data from super market

This project analyzes supermarket sales data to understand trends,customer behavior,and bussiness performance.

##1.Data cleaning and inspection
"""

# read csv file

import pandas as pd
df = pd.read_csv("SuperMarket Analysis.csv")

#first 10 rows
print(df.head(10))

#shape(rows,columns)
print(df.shape)

#data info
print(df.info())

#missing values
print(df.isnull().sum())

"""##2.Data cleaning and preparation"""

# handle missing values
df = df.dropna()

# convert Date column
df['Date'] = pd.to_datetime(df['Date'])

#create TotalSAles (if not present)
if 'TotalSales' not in df.columns:
  df['TotalSales'] = df['Quantity']*df['Unit price']

"""##3.Exploratory Data Analysis"""

#Top 3 products
top_products=(df.groupby('Product line')['TotalSales'].sum().sort_values(ascending=False).head(3))
print(top_products)

# Highest Average Sales Branch
branch_avg=df.groupby('Branch')['TotalSales'].mean()
print(branch_avg)

# customer type distribution
print(df['Customer type'].value_counts())
avg_spending=df.groupby('Customer type')['TotalSales'].mean()
print(avg_spending)

"""##4.Data visualizations"""

#1.Bar chart
import matplotlib.pyplot as plt
plt.figure()
df.groupby('Product line')['TotalSales'].sum().plot(kind='bar')
plt.title('Total Sales by Product line')
plt.xlabel('Product line')
plt.ylabel('Total Sales')
plt.show()

#2.Box plot
import seaborn as sns
plt.figure()
sns.boxplot(x="Branch",y='TotalSales',data=df)
plt.title('Total Sales by Branch')
plt.xlabel('Branch')
plt.ylabel('Total Sales')
plt.show()

#3.Histogram
plt.figure()
plt.hist(df['TotalSales'])
plt.title('Distribution of Total Sales')
plt.xlabel('Sales')
plt.ylabel('Frequency')
plt.show()

#4.Pair plot
sns.pairplot(df)
plt.show()

#5.Heatmap
plt.figure()
sns.heatmap(df.corr(numeric_only=True),annot=True)
plt.title("Correlation Heatmap")
plt.show()

"""##5.Analytical insights

##1. which product line generates consistent sales regardless of branch?

The product line shows the similar sales values across all branches can be considered consistent.From the analysis,Food and Beverages shows a stable performance across branches.

##2.Does gender have a significant influence on average sales value?

The average sales value between male and female customers does not show a significant difference.This indicates gender does not strongly influence purchasing behavior in this dataset.

##3. Suggest one insights for business decision

Top performing product lines should be stocked more,as they contribute the highest revenue.Additionally,member customers tend to spend more on average,bussiness can focus on to increase customer retention and sales.
"""