# -*- coding: utf-8 -*-
"""week_2_DA_assignmnent_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16tFm4Jse5Zx77mHTQ_qzBqfuWkGSr1eL

# **Assignemnt 2**

#Netfix Movies and TV shows Datasets

This dataset includes information on all Netflix movies and TV shows, including title, director, cast,
country, date added, release year, rating, duration, and genre.

##1. Data loading and basic checking
"""

import pandas as pd
df=pd.read_csv("netflix_titles.csv")

# first 10 rows
print(df.head(10))

#shape(rows,columns)
print('Shape:',df.shape)

#columns names
print('Columns:',df.columns)

# datatypes
print(df.dtypes)

#missing values
print('Null values:\n',df.isnull().sum())

"""##2.Data cleaning"""

# handling missing values
df['director'].fillna("Unknown",inplace=True)

df['cast'].fillna("Not Available",inplace=True)

df['country'].fillna("Unknown",inplace=True)

df.dropna(subset=['date_added'],inplace=True)

#standardize string columns
df['type']=df['type'].str.upper()

df['rating']=df['rating'].str.upper()

df['date_added']=pd.to_datetime(df['date_added'], format='mixed')

"""##3.Univariate and Bivariate Analysis"""

#most common rating
print(df['rating'].value_counts().head(1))

#Top 5 contries
print(df['country'].value_counts().head(2))

#Analyze content type
print(df.groupby('type')['release_year'].mean())

"""##4. Trend and relationship Exploration

"""

df['year_added']=df['date_added'].dt.year
titles_per_year=df.groupby('year_added').size()
print(titles_per_year)

"""##Trend observation
* Netflix content is increased in the year of 2016 to 2019
* After that it is decreased or stable

##5.Visualization
"""

import matplotlib.pyplot as plt
import seaborn as sns

# count plot
sns.countplot(x='type',data=df)
plt.show()

# bar chart
df['country'].value_counts().head(5).plot(kind='bar')
plt.show()

#line plot
titles_per_year.plot(kind='line')
plt.show()

#scatter plot
df['duration_num']=df['duration'].str.extract('(\d+)').astype(float)
plt.scatter(df['release_year'],df['duration_num'])
plt.show()

#heatmap
sns.heatmap(df.corr(numeric_only=True),annot=True)
plt.show()

"""##6.Conclusion and Insights

* Movies are more dominant than TV shows in the platform.
* The Unites states and India are the top content_producing countries.
* The highest number of titles were added between the year of 2016 to 2019.
* In recent years,the growth in content additions has slowed down.

## Recommendation

* Netflix should focus more on religinal content such as India and Korean.
* Recent content are more demand compared to old movies.
* Priority should be given to newer releases.
* The popularity of TV shows is increasing,Netflix should invest more in producing and acquiring TV series.
"""